"use client";
import { Heart, MessageSquareText, Send, Share2 } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { cloudFetch, type UserExperience } from "@/lib/agent";

type Post = { id: string; author: string; body: string; tag: string; time: string; likes: number; shares: number; comments: number; liked: boolean; shared: boolean };
type Comment = { comment_id: string; author_name: string; body: string };

export function CloudCommunityScreen({ experience, token }: { experience: UserExperience | null; token: string }) {
  const [posts, setPosts] = useState<Post[]>([]); const [draft, setDraft] = useState(""); const [tag, setTag] = useState("Thử thách tuần");
  const [notice, setNotice] = useState(""); const [open, setOpen] = useState(""); const [comments, setComments] = useState<Comment[]>([]); const [comment, setComment] = useState("");
  const stats = useMemo(() => posts.reduce((sum, post) => ({ likes: sum.likes + post.likes, shares: sum.shares + post.shares, comments: sum.comments + post.comments }), { likes: 0, shares: 0, comments: 0 }), [posts]);
  async function refresh() { try { const data = await cloudFetch<{ posts: Record<string, unknown>[] }>("/api/user/community", undefined, token); setPosts(data.posts.map(toPost)); } catch { setNotice("Không tải được Eco-Share Cloud. Vui lòng thử lại."); } }
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 5000); return () => window.clearInterval(timer); }, [token]);
  async function publish(event: FormEvent) { event.preventDefault(); if (!draft.trim()) return setNotice("Nhập nội dung trước khi đăng."); const data = await cloudFetch<{ posts: Record<string, unknown>[] }>("/api/user/community", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: draft, tag }) }, token); setPosts(data.posts.map(toPost)); setDraft(""); setNotice("Đã đăng bài lên Eco-Share."); }
  async function like(post: Post) { await cloudFetch(`/api/user/community/posts/${post.id}/like`, { method: post.liked ? "DELETE" : "POST" }, token); await refresh(); }
  async function repost(post: Post) { await cloudFetch(`/api/user/community/posts/${post.id}/repost`, { method: "POST" }, token); await refresh(); setNotice(post.shared ? "Bạn đã chia sẻ bài này." : "Đã đăng lại lên Eco-Share."); }
  async function showComments(id: string) { const data = await cloudFetch<{ comments: Comment[] }>(`/api/user/community/posts/${id}/comments`, undefined, token); setComments(data.comments); setOpen(id); }
  async function sendComment(id: string) { if (!comment.trim()) return; const data = await cloudFetch<{ comments: Comment[] }>(`/api/user/community/posts/${id}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: comment }) }, token); setComments(data.comments); setComment(""); await refresh(); }
  return <section className="community-layout">
    <div className="user-card-grid community-summary-grid">{(experience?.community_cards ?? []).map(card => <article className={`user-panel community-card ${card.tone}`} key={card.id}><span className="eyebrow">Eco-Share Cloud</span><strong>{card.title}</strong><p>{card.message}</p><b>{card.metric}</b></article>)}</div>
    <section className="user-panel social-composer-panel"><div className="user-panel-heading inline"><div><span className="eyebrow">Cộng đồng nội bộ</span><strong>Đăng bài Eco-Share</strong></div><MessageSquareText size={21}/></div><form className="social-composer" onSubmit={publish}><label>Chủ đề<select value={tag} onChange={e=>setTag(e.target.value)}><option>Thử thách tuần</option><option>Cạnh tranh</option><option>Mẹo xanh</option><option>Eco Score</option></select></label><label>Nội dung<textarea maxLength={500} placeholder="Chia sẻ thành tích hoặc mẹo xanh..." value={draft} onChange={e=>setDraft(e.target.value)}/></label><div className="social-composer-actions"><span>{notice || `${stats.likes} lượt thích, ${stats.shares} lượt chia sẻ, ${stats.comments} bình luận`}</span><button className="primary-button" type="submit"><Send size={16}/><span>Đăng bài</span></button></div></form></section>
    <section className="social-feed">{posts.length ? posts.map(post => <article className="user-panel social-post-card" key={post.id}><header><div><strong>{post.author}</strong><span>{post.time} - {post.tag}</span></div></header><p>{post.body}</p><div className="social-post-actions"><button className={post.liked ? "active" : ""} onClick={()=>void like(post)} type="button"><Heart fill={post.liked ? "currentColor" : "none"} size={16}/><span>{post.likes}</span></button><button className={post.shared ? "active" : ""} onClick={()=>void repost(post)} type="button"><Share2 size={16}/><span>{post.shares}</span></button><button onClick={()=>void showComments(post.id)} type="button"><MessageSquareText size={16}/><span>{post.comments}</span></button></div>{open===post.id?<div className="social-comment-thread">{comments.map(item=><p key={item.comment_id}><strong>{item.author_name}</strong> {item.body}</p>)}<div><input maxLength={300} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Viết bình luận..."/><button onClick={()=>void sendComment(post.id)} type="button">Gửi</button></div></div>:null}</article>):<div className="empty-state">Chưa có bài viết. Hãy đăng bài đầu tiên.</div>}</section>
  </section>;
}
function toPost(row: Record<string, unknown>): Post { return { id:String(row.post_id), author:String(row.author_name), body:String(row.body), tag:String(row.tag), time:new Date(String(row.created_at)).toLocaleString("vi-VN"), likes:Number(row.likes), shares:Number(row.shares), comments:Number(row.comments), liked:Boolean(row.liked_by_me), shared:Boolean(row.shared_by_me) }; }
